import { jsPDF } from 'jspdf';
import { Trip } from '../types';
import { getCurrencySymbol } from './currency';

export function exportTripToPdf(trip: Trip) {
  const doc = new jsPDF();
  const symbol = getCurrencySymbol(trip.currency);
  let y = 15;

  // Header Banner
  doc.setFillColor(15, 23, 42); // dark blue background
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(`EASYTRIP AI - ITINERARY`, 14, 18);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${trip.destination}, ${trip.country} (${trip.durationDays} Days)`, 14, 28);

  y = 45;

  // Trip Summary Box
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(14, y, 182, 28, 3, 3, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`TRIP OVERVIEW`, 18, y + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Dates: ${trip.startDate || 'TBD'} to ${trip.endDate || 'TBD'}  |  Travelers: ${trip.travelersCount} (${trip.travelerType})  |  Budget: ${symbol}${trip.totalBudget ? trip.totalBudget.toLocaleString() : ''} (${trip.budgetLevel.toUpperCase()})`, 18, y + 15);

  const splitSummary = doc.splitTextToSize(trip.summary || '', 174);
  doc.text(splitSummary, 18, y + 21);

  y += 36;

  // Itinerary Days
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('DAY-BY-DAY ITINERARY', 14, y);
  y += 8;

  trip.itinerary.forEach((day) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFillColor(224, 231, 255);
    doc.rect(14, y, 182, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(30, 58, 138);
    doc.text(`DAY ${day.dayNumber}: ${day.theme.toUpperCase()}`, 18, y + 5);
    y += 10;

    day.activities.forEach((act) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(15, 23, 42);
      const costText = act.estimatedCost > 0 ? ` [Est. ${symbol}${act.estimatedCost.toLocaleString()}]` : '';
      doc.text(`• ${act.time} - ${act.title}${costText}`, 18, y);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      const descLines = doc.splitTextToSize(`${act.description} (Loc: ${act.locationName})`, 170);
      doc.text(descLines, 22, y + 4);
      
      y += 6 + (descLines.length * 3.5);
    });

    y += 4;
  });

  // Emergency Contacts & Packing List Page
  if (y > 200) {
    doc.addPage();
    y = 20;
  } else {
    y += 10;
  }

  // Packing Checklist
  if (trip.packingList && trip.packingList.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('RECOMMENDED PACKING LIST', 14, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(51, 65, 85);

    const packingNames = trip.packingList.map(p => `${p.packed ? '[x]' : '[ ]'} ${p.name} (${p.category})`).join('   |   ');
    const packingLines = doc.splitTextToSize(packingNames, 182);
    doc.text(packingLines, 14, y);

    y += (packingLines.length * 4) + 10;
  }

  // Emergency Contacts
  if (trip.emergencyContacts && trip.emergencyContacts.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('EMERGENCY CONTACTS', 14, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(185, 28, 28);

    trip.emergencyContacts.forEach((contact) => {
      doc.text(`• ${contact.type}: ${contact.name} - Phone: ${contact.phone}`, 14, y);
      y += 5;
    });
  }

  // Footer Note
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by EasyTrip AI on ${new Date().toLocaleDateString()}`, 14, 285);

  doc.save(`${trip.destination.toLowerCase().replace(/[^a-z0-9]/g, '_')}_easytrip_itinerary.pdf`);
}
