import React, { createContext, useContext, useState, useEffect } from 'react';

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag?: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'fr', name: 'French', nativeName: 'Français' },
  { code: 'es', name: 'Spanish', nativeName: 'Español' },
  { code: 'de', name: 'German', nativeName: 'Deutsch' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語' },
];

// UI Translations Dictionary
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    brandName: 'EasyTrip',
    brandTagline: 'Smart Itinerary Companion',
    navDashboard: 'Dashboard',
    navPlanner: 'AI Trip Planner',
    navCurrentTrip: 'Current Trip',
    navProfile: 'Profile',
    askAI: 'Ask AI',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    welcomeTitle: 'Welcome back',
    welcomeSubtitle: 'Where would you like to travel next?',
    createTripBtn: 'Plan New Trip',
    myTrips: 'My Trips',
    quickStats: 'Trip Overview',
    totalTrips: 'Total Trips',
    noTripsYet: 'No trips created yet',
    startPlanning: 'Start planning your dream adventure with AI.',
    viewDetails: 'View Itinerary',
    exportPdf: 'Export PDF',
    deleteTrip: 'Delete',
    plannerTitle: 'Design Your Dream Trip',
    plannerSubtitle: 'AI creates personalized, day-by-day itineraries with maps, budget estimates, hotels & hidden gems.',
    destinationLabel: 'Destination',
    destinationPlaceholder: 'e.g., Tokyo, Paris, Goa, Kyoto...',
    datesLabel: 'Travel Dates',
    startDate: 'Start Date',
    endDate: 'End Date',
    durationDays: 'Days',
    currencyAndBudget: 'Currency & Target Budget',
    budgetTier: 'Budget Tier',
    travelerGroup: 'Traveler Group',
    interestsLabel: 'Interests & Vibe',
    generateTripBtn: 'Generate Itinerary with AI',
    generatingTrip: 'Crafting Your Custom Travel Experience...',
    tabItinerary: 'Itinerary Schedule',
    tabMap: 'Interactive Map',
    tabHotels: 'Hotel Stays',
    tabWeather: 'Weather Outlook',
    tabPacking: 'Packing Checklist',
    tabFood: 'Food Guide',
    tabGems: 'Hidden Gems',
    tabBudget: 'Budget Analytics',
    tabEmergency: 'Safety & Emergency',
    tabExpenses: 'Expense Splitter',
    day: 'Day',
    chatTitle: 'EasyTrip AI Assistant',
    chatSubtitle: 'Your 24/7 smart travel assistant',
    chatPlaceholder: 'Ask anything about your destination or trip...',
    send: 'Send',
    languagePref: 'Preferred Language',
    currencyPref: 'Preferred Currency',
    profileTitle: 'Traveler Profile',
    budgetLabel: 'Budget',
    moderateLabel: 'Moderate',
    luxuryLabel: 'Luxury',
    solo: 'Solo',
    couple: 'Couple',
    family: 'Family',
    friends: 'Friends'
  },
  ta: {
    brandName: 'ஈஸிட்ரிப்',
    brandTagline: 'ஸ்மார்ட் பயண வழிகாட்டி',
    navDashboard: 'முகப்பு',
    navPlanner: 'AI பயணத் திட்டமிடுபவர்',
    navCurrentTrip: 'தற்போதைய பயணம்',
    navProfile: 'சுயவிவரம்',
    askAI: 'AI இடம் கேளுங்கள்',
    signIn: 'உள்நுழைக',
    signOut: 'வெளியேறு',
    welcomeTitle: 'மீண்டும் வருக',
    welcomeSubtitle: 'அடுத்து எங்கு பயணம் செய்ய விரும்புகிறீர்கள்?',
    createTripBtn: 'புதிய பயணம் திட்டமிடுக',
    myTrips: 'என் பயணங்கள்',
    quickStats: 'பயண மேலோட்டம்',
    totalTrips: 'மொத்த பயணங்கள்',
    noTripsYet: 'இன்னும் பயணங்கள் எதுவும் உருவாக்கப்படவில்லை',
    startPlanning: 'AI மூலம் உங்கள் கனவு பயணத்தை திட்டமிட தொடங்குங்கள்.',
    viewDetails: 'திட்டத்தைப் பார்க்கவும்',
    exportPdf: 'PDF ஏற்றுமதி',
    deleteTrip: 'நீக்கு',
    plannerTitle: 'உங்கள் கனவு பயணத்தை வடிவமையுங்கள்',
    plannerSubtitle: 'AI வரைபடங்கள், வரவு செலவு, ஹோட்டல்கள் மற்றும் மறைந்திருக்கும் ரத்தினங்களுடன் தனிப்பயனாக்கப்பட்ட திட்டத்தை உருவாக்குகிறது.',
    destinationLabel: 'செல்லுமிடம்',
    destinationPlaceholder: 'எ.கா., டோக்கியோ, பாரிஸ், கோவா...',
    datesLabel: 'பயண தேதிகள்',
    startDate: 'தொடக்க தேதி',
    endDate: 'முடிவு தேதி',
    durationDays: 'நாட்கள்',
    currencyAndBudget: 'நாணயம் & இலக்கு வரவு செலவு',
    budgetTier: 'பஜெட் நிலை',
    travelerGroup: 'பயணிகள் குழு',
    interestsLabel: 'ஆர்வங்கள்',
    generateTripBtn: 'AI மூலம் பயணத்திட்டம் உருவாக்குங்கள்',
    generatingTrip: 'உங்கள் பயணத் திட்டம் உருவாக்கப்படுகிறது...',
    tabItinerary: 'நாட்குறிப்பு திட்டம்',
    tabMap: 'வரைபடம்',
    tabHotels: 'ஹோட்டல்கள்',
    tabWeather: 'வானிலை முன்கணிப்பு',
    tabPacking: 'பொருட்கள் பட்டியல்',
    tabFood: 'உணவு வழிகாட்டி',
    tabGems: 'மறைந்த இடங்கள்',
    tabBudget: 'பஜெட் பகுப்பாய்வு',
    tabEmergency: 'அவசர தொடர்புகள்',
    tabExpenses: 'செலவு பிரிப்பான்',
    day: 'நாள்',
    chatTitle: 'ஈஸிட்ரிப் AI உதவியாளர்',
    chatSubtitle: 'உங்கள் 24/7 ஸ்மார்ட் பயண உதவியாளர்',
    chatPlaceholder: 'உங்கள் பயணம் பற்றி எதையும் கேளுங்கள்...',
    send: 'அனுப்பு',
    languagePref: 'விருப்பமான மொழி',
    currencyPref: 'விருப்பமான நாணயம்',
    profileTitle: 'பயணி சுயவிவரம்',
    budgetLabel: 'சிக்கனம்',
    moderateLabel: 'மிதமான',
    luxuryLabel: 'ஆடம்பரம்',
    solo: 'தனியாக',
    couple: 'ஜோடி',
    family: 'குடும்பம்',
    friends: 'நண்பர்கள்'
  },
  hi: {
    brandName: 'इज़ीट्रिप',
    brandTagline: 'स्मार्ट यात्रा साथी',
    navDashboard: 'डैशबोर्ड',
    navPlanner: 'AI यात्रा योजनाकार',
    navCurrentTrip: 'वर्तमान यात्रा',
    navProfile: 'प्रोफ़ाइल',
    askAI: 'AI से पूछें',
    signIn: 'साइन इन करें',
    signOut: 'साइन आउट',
    welcomeTitle: 'पुनः स्वागत है',
    welcomeSubtitle: 'आप आगे कहाँ यात्रा करना चाहते हैं?',
    createTripBtn: 'नई यात्रा की योजना बनाएं',
    myTrips: 'मेरी यात्राएं',
    quickStats: 'यात्रा अवलोकन',
    totalTrips: 'कुल यात्राएं',
    noTripsYet: 'अभी तक कोई यात्रा नहीं बनाई गई है',
    startPlanning: 'AI के साथ अपनी सपनों की यात्रा की योजना बनाना शुरू करें।',
    viewDetails: 'यात्रा कार्यक्रम देखें',
    exportPdf: 'PDF निर्यात करें',
    deleteTrip: 'हटाएं',
    plannerTitle: 'अपनी सपनों की यात्रा डिज़ाइन करें',
    plannerSubtitle: 'AI मानचित्रों, बजट अनुमानों, होटलों और छिपे हुए स्थानों के साथ व्यक्तिगत यात्रा कार्यक्रम तैयार करता है।',
    destinationLabel: 'गंतव्य',
    destinationPlaceholder: 'जैसे, टोक्यो, पेरिस, गोवा, जयपुर...',
    datesLabel: 'यात्रा तिथियां',
    startDate: 'प्रारंभ तिथि',
    endDate: 'अंतिम तिथि',
    durationDays: 'दिन',
    currencyAndBudget: 'मुद्रा और लक्षित बजट',
    budgetTier: 'बजट स्तर',
    travelerGroup: 'यात्री समूह',
    interestsLabel: 'रुचियां',
    generateTripBtn: 'AI के साथ यात्रा कार्यक्रम बनाएं',
    generatingTrip: 'आपका व्यक्तिगत यात्रा अनुभव तैयार किया जा रहा है...',
    tabItinerary: 'यात्रा कार्यक्रम',
    tabMap: 'मानचित्र',
    tabHotels: 'होटल',
    tabWeather: 'मौसम का पूर्वानुमान',
    tabPacking: 'पैकिंग सूची',
    tabFood: 'भोजन गाइड',
    tabGems: 'छिपे हुए स्थान',
    tabBudget: 'बजट विश्लेषण',
    tabEmergency: 'आपातकालीन सुरक्षा',
    tabExpenses: 'खर्च विभाजक',
    day: 'दिन',
    chatTitle: 'इज़ीट्रिप AI सहायक',
    chatSubtitle: 'आपका 24/7 स्मार्ट यात्रा सहायक',
    chatPlaceholder: 'अपनी यात्रा के बारे में कुछ भी पूछें...',
    send: 'भेजें',
    languagePref: 'पसंदीदा भाषा',
    currencyPref: 'पसंदीदा मुद्रा',
    profileTitle: 'यात्री प्रोफ़ाइल',
    budgetLabel: 'बजट',
    moderateLabel: 'मध्यम',
    luxuryLabel: 'लक्जरी',
    solo: 'अकेले',
    couple: 'जोड़ा',
    family: 'परिवार',
    friends: 'मित्र'
  },
  ml: {
    brandName: 'ഈസിട്രിപ്പ്',
    brandTagline: 'സ്മാർട്ട് യാത്രാ സഹായി',
    navDashboard: 'ഡാഷ്‌ബോർഡ്',
    navPlanner: 'AI യാത്രാ പ്ലാനർ',
    navCurrentTrip: 'ഇപ്പോഴത്തെ യാത്ര',
    navProfile: 'പ്രൊഫൈൽ',
    askAI: 'AI-യോട് ചോദിക്കുക',
    signIn: 'സൈൻ ഇൻ ചെയ്യുക',
    signOut: 'സൈൻ ഔട്ട്',
    welcomeTitle: 'സ്വാഗതം',
    welcomeSubtitle: 'അടുത്തതായി എവിടേക്ക് യാത്ര ചെയ്യാൻ ആഗ്രഹിക്കുന്നു?',
    createTripBtn: 'പുതിയ യാത്ര പ്ലാൻ ചെയ്യുക',
    myTrips: 'എന്റെ യാത്രകൾ',
    quickStats: 'യാത്രാ അവലോകനം',
    totalTrips: 'ആകെ യാത്രകൾ',
    noTripsYet: 'ഇതുവരെ യാത്രകളൊന്നും ഉണ്ടാക്കിയിട്ടില്ല',
    startPlanning: 'AI ഉപയോഗിച്ച് നിങ്ങളുടെ സ്വപ്ന യാത്ര പ്ലാൻ ചെയ്യാൻ തുടങ്ങുക.',
    viewDetails: 'യാത്രാ വിവരങ്ങൾ കാണുക',
    exportPdf: 'PDF എക്സ്പോർട്ട് ചെയ്യുക',
    deleteTrip: 'ഡിലീറ്റ് ചെയ്യുക',
    plannerTitle: 'നിങ്ങളുടെ സ്വപ്ന യാത്ര രൂപകൽപ്പന ചെയ്യുക',
    plannerSubtitle: 'മാപ്പുകൾ, ബജറ്റ്, ഹോട്ടലുകൾ എന്നിവയടങ്ങിയ യാത്രാ പ്ലാൻ AI നിർമ്മിക്കുന്നു.',
    destinationLabel: 'ലക്ഷ്യസ്ഥാനം',
    destinationPlaceholder: 'ഉദാഹരണത്തിന്, ടോക്കിയോ, പാരീസ്, ഗോവ...',
    datesLabel: 'യാത്രാ തീയതികൾ',
    startDate: 'തുടക്ക തീയതി',
    endDate: 'അവസാന തീയതി',
    durationDays: 'ദിവസങ്ങൾ',
    currencyAndBudget: 'കറൻസിയും ബജറ്റും',
    budgetTier: 'ബജറ്റ് തരം',
    travelerGroup: 'യാത്രാ സംഘം',
    interestsLabel: 'താല്പര്യങ്ങൾ',
    generateTripBtn: 'AI യാത്രാ പ്ലാൻ ഉണ്ടാക്കുക',
    generatingTrip: 'നിങ്ങളുടെ യാത്രാ പ്ലാൻ തയ്യാറാക്കുന്നു...',
    tabItinerary: 'യാത്രാ ഷെഡ്യൂൾ',
    tabMap: 'മാപ്പ്',
    tabHotels: 'ഹോട്ടലുകൾ',
    tabWeather: 'കാലാവസ്ഥ',
    tabPacking: 'പാക്കിംഗ് ലിസ്റ്റ്',
    tabFood: 'ഭക്ഷണ ഗൈഡ്',
    tabGems: 'പ്രത്യേക സ്ഥലങ്ങൾ',
    tabBudget: 'ബജറ്റ് അപഗ്രഥനം',
    tabEmergency: 'അടിയന്തര സഹായം',
    tabExpenses: 'ചെലവ് വിഭജനം',
    day: 'ദിവസം',
    chatTitle: 'ഈസിട്രിപ്പ് AI അസിസ്റ്റന്റ്',
    chatSubtitle: 'നിങ്ങളുടെ 24/7 സ്മാർട്ട് യാത്രാ സഹായി',
    chatPlaceholder: 'യാത്രയെക്കുറിച്ച് എന്തും ചോദിക്കാം...',
    send: 'അയക്കുക',
    languagePref: 'ഇഷ്ടപ്പെട്ട ഭാഷ',
    currencyPref: 'ഇഷ്ടപ്പെട്ട കറൻസി',
    profileTitle: 'യാത്രക്കാരന്റെ പ്രൊഫൈൽ',
    budgetLabel: 'സാധാരണ',
    moderateLabel: 'മിതമായ',
    luxuryLabel: 'ആഡംബരം',
    solo: 'ഒറ്റയ്ക്ക്',
    couple: 'ദമ്പതികൾ',
    family: 'കുടുംബം',
    friends: 'കൂട്ടുകാർ'
  },
  te: {
    brandName: 'ఈజీట్రిప్',
    brandTagline: 'స్మార్ట్ ప్రయాణ సహాయకుడు',
    navDashboard: 'డాష్‌బోర్డ్',
    navPlanner: 'AI ప్రయాణ ప్రణాళిక',
    navCurrentTrip: 'ప్రస్తుత ప్రయాణం',
    navProfile: 'ప్రొఫైల్',
    askAI: 'AI ని అడగండి',
    signIn: 'సైన్ ఇన్',
    signOut: 'సైన్ అవుట్',
    welcomeTitle: 'తిరిగి స్వాగతం',
    welcomeSubtitle: 'తరువాత మీరు ఎక్కడికి ప్రయాణించాలనుకుంటున్నారు?',
    createTripBtn: 'కొత్త ప్రయాణ ప్రణాళిక',
    myTrips: 'నా ప్రయాణాలు',
    quickStats: 'ప్రయాణ సమగ్రం',
    totalTrips: 'మొత్తం ప్రయాణాలు',
    noTripsYet: 'ఇంకా ఎలాంటి ప్రయాణాలు సృష్టించబడలేదు',
    startPlanning: 'AI తో మీ డ్రీమ్ ప్రయాణాన్ని ప్రారంభించండి.',
    viewDetails: 'ప్రణాళిక చూడండి',
    exportPdf: 'PDF ఎగుమతి',
    deleteTrip: 'తొలగించు',
    plannerTitle: 'మీ డ్రీమ్ ట్రిప్‌ను రూపొందించండి',
    plannerSubtitle: 'AI మ్యాప్‌లు, బడ్జెట్ అంచనాలు, హోటళ్ళు మరియు గుప్త ప్రదేశాలతో ప్రణాళికను తయారు చేస్తుంది.',
    destinationLabel: 'గమ్యస్థానం',
    destinationPlaceholder: 'ఉదా., టోక్యో, ప్యారిస్, గోవా...',
    datesLabel: 'ప్రయాణ తేదీలు',
    startDate: 'ప్రారంభ తేదీ',
    endDate: 'ముగింపు తేదీ',
    durationDays: 'రోజులు',
    currencyAndBudget: 'కరెన్సీ & బడ్జెట్',
    budgetTier: 'బడ్జెట్ స్థాయి',
    travelerGroup: 'ప్రయాణీకుల సమూహం',
    interestsLabel: 'ఆసక్తులు',
    generateTripBtn: 'AI తో ప్రణాళిక సృష్టించండి',
    generatingTrip: 'మీ ప్రయాణ ప్రణాళిక సిద్ధమవుతోంది...',
    tabItinerary: 'షెడ్యూల్',
    tabMap: 'మ్యాప్',
    tabHotels: 'హోటళ్ళు',
    tabWeather: 'వాతావరణం',
    tabPacking: 'ప్యాకింగ్ జాబితా',
    tabFood: 'ఆహార గైడ్',
    tabGems: 'ప్రత్యేక ప్రదేశాలు',
    tabBudget: 'బడ్జెట్ విశ్లేషణ',
    tabEmergency: 'అత్యవసర రక్షణ',
    tabExpenses: 'ఖర్చుల విభజన',
    day: 'రోజు',
    chatTitle: 'ఈజీట్రిప్ AI సహాయకుడు',
    chatSubtitle: 'మీ 24/7 స్మార్ట్ ప్రయాణ సహాయకుడు',
    chatPlaceholder: 'మీ ప్రయాణం గురించి ఏదైనా అడగండి...',
    send: 'పంపు',
    languagePref: 'ఎంచుకున్న భాష',
    currencyPref: 'ఎంచుకున్న కరెన్సీ',
    profileTitle: 'ప్రయాణీకుల ప్రొఫైల్',
    budgetLabel: 'బడ్జెట్',
    moderateLabel: 'మధ్యస్థం',
    luxuryLabel: 'విలాసవంతమైన',
    solo: 'ఒంటరిగా',
    couple: 'జంట',
    family: 'కుటుంబం',
    friends: 'స్నేహితులు'
  },
  kn: {
    brandName: 'ಈಸಿಟ್ರಿಪ್',
    brandTagline: 'ಸ್ಮಾರ್ಟ್ ಪ್ರವಾಸ ಸಂಗಾತಿ',
    navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navPlanner: 'AI ಪ್ರವಾಸ ಯೋಜಕ',
    navCurrentTrip: 'ಪ್ರಸ್ತುತ ಪ್ರವಾಸ',
    navProfile: 'ಪ್ರೊಫೈಲ್',
    askAI: 'AI ಕೇಳಿ',
    signIn: 'ಸೈನ್ ಇನ್',
    signOut: 'ಸೈನ್ ഔട്ട്',
    welcomeTitle: 'ಸುಸ್ವಾಗತ',
    welcomeSubtitle: 'ಮುಂದೆ ಎಲ್ಲಿಗೆ ಪ್ರವಾಸ ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
    createTripBtn: 'ಹೊಸ ಪ್ರವಾಸ ಯೋಜಿಸಿ',
    myTrips: 'ನನ್ನ ಪ್ರವಾಸಗಳು',
    quickStats: 'ಪ್ರವಾಸದ ಅವಲೋಕನ',
    totalTrips: 'ಒಟ್ಟು ಪ್ರವಾಸಗಳು',
    noTripsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಪ್ರವಾಸಗಳನ್ನು ರಚಿಸಲಾಗಿಲ್ಲ',
    startPlanning: 'AI ನೊಂದಿಗೆ ನಿಮ್ಮ ಕನಸಿನ ಪ್ರವಾಸವನ್ನು ಯೋಜಿಸಲು ಪ್ರಾರಂಭಿಸಿ.',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    exportPdf: 'PDF ರಫ್ತು ಮಾಡಿ',
    deleteTrip: 'ಅಳಿಸಿ',
    plannerTitle: 'ನಿಮ್ಮ ಕನಸಿನ ಪ್ರವಾಸವನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸಿ',
    plannerSubtitle: 'AI ನಕ್ಷೆಗಳು, ಬಜೆಟ್, ಹೋಟೆಲ್‌ಗಳು ಮತ್ತು ಗುಪ್ತ ತಾಣಗಳೊಂದಿಗೆ ಯೋಜನೆಯನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.',
    destinationLabel: 'ಗಮ್ಯಸ್ಥಾನ',
    destinationPlaceholder: 'ಉದಾ., ಟೋಕಿಯೋ, ಪ್ಯಾರಿಸ್, ಗೋವಾ...',
    datesLabel: 'ಪ್ರವಾಸದ ದಿನಾಂಕಗಳು',
    startDate: 'ಆರಂಭದ ದಿನಾಂಕ',
    endDate: 'ಕೊನೆಯ ದಿನಾಂಕ',
    durationDays: 'ದಿನಗಳು',
    currencyAndBudget: 'ಕರೆನ್ಸಿ ಮತ್ತು ಬಜೆಟ್',
    budgetTier: 'ಬಜೆಟ್ ಹಂತ',
    travelerGroup: 'ಪ್ರವಾಸಿಗರ ಗುಂಪು',
    interestsLabel: 'ಆಸಕ್ತಿಗಳು',
    generateTripBtn: 'AI ಯೊಂದಿಗೆ ಯೋಜನೆಯನ್ನು ರಚಿಸಿ',
    generatingTrip: 'ನಿಮ್ಮ ಪ್ರವಾಸದ ಯೋಜನೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ...',
    tabItinerary: 'ದಿನಚರಿ ಯೋಜನೆ',
    tabMap: 'ನಕ್ಷೆ',
    tabHotels: 'ಹೋಟೆಲ್‌ಗಳು',
    tabWeather: 'ಹವಾಮಾನ',
    tabPacking: 'ಪ್ಯಾಕಿಂಗ್ ಪಟ್ಟಿ',
    tabFood: 'ಆಹಾರ ಮಾರ್ಗದರ್ಶಿ',
    tabGems: 'ವಿಶೇಷ ತಾಣಗಳು',
    tabBudget: 'ಬಜೆಟ್ ವಿಶ್ಲೇಷಣೆ',
    tabEmergency: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    tabExpenses: 'ಖರ್ಚು ವಿಭಜನೆ',
    day: 'ದಿನ',
    chatTitle: 'ಈಸಿಟ್ರಿಪ್ AI ಸಹಾಯಕ',
    chatSubtitle: 'ನಿಮ್ಮ 24/7 ಸ್ಮಾರ್ಟ್ ಪ್ರವಾಸ ಸಹಾಯಕ',
    chatPlaceholder: 'ನಿಮ್ಮ ಪ್ರವಾಸದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    languagePref: 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    currencyPref: 'ಆದ್ಯತೆಯ ಕರೆನ್ಸಿ',
    profileTitle: 'ಪ್ರವಾಸಿಗರ ಪ್ರೊಫೈಲ್',
    budgetLabel: 'ಬಜೆಟ್',
    moderateLabel: 'ಮಧ್ಯಮ',
    luxuryLabel: 'ಐಷಾರಾಮಿ',
    solo: 'ಒಬ್ಬರೇ',
    couple: 'ದಂಪತಿಗಳು',
    family: 'ಕುಟುಂಬ',
    friends: 'ಸ್ನೇಹಿತರು'
  },
  fr: {
    brandName: 'EasyTrip',
    brandTagline: 'Compagnon d\'itinéraire intelligent',
    navDashboard: 'Tableau de bord',
    navPlanner: 'Planificateur AI',
    navCurrentTrip: 'Voyage actuel',
    navProfile: 'Profil',
    askAI: 'Demander à l\'IA',
    signIn: 'Connexion',
    signOut: 'Déconnexion',
    welcomeTitle: 'Bon retour',
    welcomeSubtitle: 'Où souhaitez-vous voyager ensuite ?',
    createTripBtn: 'Nouveau voyage',
    myTrips: 'Mes voyages',
    quickStats: 'Aperçu du voyage',
    totalTrips: 'Total des voyages',
    noTripsYet: 'Aucun voyage créé pour le moment',
    startPlanning: 'Planifiez le voyage de vos rêves avec l\'IA.',
    viewDetails: 'Voir l\'itinéraire',
    exportPdf: 'Exporter en PDF',
    deleteTrip: 'Supprimer',
    plannerTitle: 'Créez votre voyage de rêve',
    plannerSubtitle: 'L\'IA crée des itinéraires personnalisés jour par jour avec cartes, budgets, hôtels et joyaux cachés.',
    destinationLabel: 'Destination',
    destinationPlaceholder: 'ex: Tokyo, Paris, Nice, Kyoto...',
    datesLabel: 'Dates du voyage',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    durationDays: 'Jours',
    currencyAndBudget: 'Devise et budget cible',
    budgetTier: 'Niveau de budget',
    travelerGroup: 'Groupe de voyageurs',
    interestsLabel: 'Centres d\'intérêt',
    generateTripBtn: 'Générer l\'itinéraire avec l\'IA',
    generatingTrip: 'Création de votre itinéraire sur mesure...',
    tabItinerary: 'Itinéraire',
    tabMap: 'Carte interactive',
    tabHotels: 'Hôtels',
    tabWeather: 'Météo',
    tabPacking: 'Liste de bagages',
    tabFood: 'Guide culinaire',
    tabGems: 'Lieux secrets',
    tabBudget: 'Analyse du budget',
    tabEmergency: 'Sécurité et urgences',
    tabExpenses: 'Partage des frais',
    day: 'Jour',
    chatTitle: 'Assistant EasyTrip AI',
    chatSubtitle: 'Votre assistant de voyage intelligent 24/7',
    chatPlaceholder: 'Posez n\'importe quelle question sur votre voyage...',
    send: 'Envoyer',
    languagePref: 'Langue préférée',
    currencyPref: 'Devise préférée',
    profileTitle: 'Profil du voyageur',
    budgetLabel: 'Économique',
    moderateLabel: 'Modéré',
    luxuryLabel: 'Luxe',
    solo: 'Solo',
    couple: 'En couple',
    family: 'En famille',
    friends: 'Entre amis'
  },
  es: {
    brandName: 'EasyTrip',
    brandTagline: 'Compañero inteligente de viajes',
    navDashboard: 'Panel principal',
    navPlanner: 'Planificador IA',
    navCurrentTrip: 'Viaje actual',
    navProfile: 'Perfil',
    askAI: 'Preguntar a la IA',
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    welcomeTitle: 'Bienvenido de nuevo',
    welcomeSubtitle: '¿A dónde te gustaría viajar ahora?',
    createTripBtn: 'Planificar nuevo viaje',
    myTrips: 'Mis viajes',
    quickStats: 'Resumen de viajes',
    totalTrips: 'Viajes totales',
    noTripsYet: 'Aún no se han creado viajes',
    startPlanning: 'Comienza a planificar tu viaje soñado con IA.',
    viewDetails: 'Ver itinerario',
    exportPdf: 'Exportar PDF',
    deleteTrip: 'Eliminar',
    plannerTitle: 'Diseña el viaje de tus sueños',
    plannerSubtitle: 'La IA crea itinerarios personalizados día a día con mapas, presupuestos, hoteles y joyas ocultas.',
    destinationLabel: 'Destino',
    destinationPlaceholder: 'ej. Tokio, París, Barcelona, Cancún...',
    datesLabel: 'Fechas de viaje',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    durationDays: 'Días',
    currencyAndBudget: 'Moneda y presupuesto objetivo',
    budgetTier: 'Nivel de presupuesto',
    travelerGroup: 'Grupo de viajeros',
    interestsLabel: 'Intereses',
    generateTripBtn: 'Generar itinerario con IA',
    generatingTrip: 'Creando tu experiencia de viaje personalizada...',
    tabItinerary: 'Itinerario',
    tabMap: 'Mapa interactivo',
    tabHotels: 'Hoteles',
    tabWeather: 'Clima',
    tabPacking: 'Lista de equipaje',
    tabFood: 'Guía gastronómica',
    tabGems: 'Lugares secretos',
    tabBudget: 'Análisis de presupuesto',
    tabEmergency: 'Emergencias y seguridad',
    tabExpenses: 'División de gastos',
    day: 'Día',
    chatTitle: 'Asistente EasyTrip AI',
    chatSubtitle: 'Tu asistente de viajes inteligente 24/7',
    chatPlaceholder: 'Pregunta cualquier cosa sobre tu viaje...',
    send: 'Enviar',
    languagePref: 'Idioma preferido',
    currencyPref: 'Moneda preferida',
    profileTitle: 'Perfil del viajero',
    budgetLabel: 'Económico',
    moderateLabel: 'Moderado',
    luxuryLabel: 'Lujo',
    solo: 'Solo',
    couple: 'En pareja',
    family: 'En familia',
    friends: 'Con amigos'
  },
  de: {
    brandName: 'EasyTrip',
    brandTagline: 'Intelligenter Reisebegleiter',
    navDashboard: 'Dashboard',
    navPlanner: 'KI Reiseplaner',
    navCurrentTrip: 'Aktuelle Reise',
    navProfile: 'Profil',
    askAI: 'KI fragen',
    signIn: 'Anmelden',
    signOut: 'Abmelden',
    welcomeTitle: 'Willkommen zurück',
    welcomeSubtitle: 'Wohin möchten Sie als Nächstes reisen?',
    createTripBtn: 'Neue Reise planen',
    myTrips: 'Meine Reisen',
    quickStats: 'Reiseübersicht',
    totalTrips: 'Gesamte Reisen',
    noTripsYet: 'Noch keine Reisen erstellt',
    startPlanning: 'Planen Sie Ihre Traumreise mit KI.',
    viewDetails: 'Reiseplan anzeigen',
    exportPdf: 'PDF exportieren',
    deleteTrip: 'Löschen',
    plannerTitle: 'Gestalten Sie Ihre Traumreise',
    plannerSubtitle: 'KI erstellt personalisierte Tagesreisepläne mit Karten, Budgetschätzungen, Hotels & Geheimtipps.',
    destinationLabel: 'Reiseziel',
    destinationPlaceholder: 'z.B. Tokio, Paris, Berlin, Kyoto...',
    datesLabel: 'Reisedaten',
    startDate: 'Startdatum',
    endDate: 'Enddatum',
    durationDays: 'Tage',
    currencyAndBudget: 'Währung & Zielbudget',
    budgetTier: 'Budgetklasse',
    travelerGroup: 'Reisegruppe',
    interestsLabel: 'Interessen',
    generateTripBtn: 'Reiseplan mit KI erstellen',
    generatingTrip: 'Erstelle Ihr individuelles Reiseerlebnis...',
    tabItinerary: 'Tagesplan',
    tabMap: 'Interaktive Karte',
    tabHotels: 'Hotels',
    tabWeather: 'Wetterbericht',
    tabPacking: 'Packliste',
    tabFood: 'Kulinarischer Guide',
    tabGems: 'Geheimtipps',
    tabBudget: 'Budgetanalyse',
    tabEmergency: 'Sicherheit & Notfall',
    tabExpenses: 'Kostenaufteilung',
    day: 'Tag',
    chatTitle: 'EasyTrip KI Assistent',
    chatSubtitle: 'Ihr intelligenter 24/7 Reisebegleiter',
    chatPlaceholder: 'Fragen Sie alles über Ihr Reiseziel...',
    send: 'Senden',
    languagePref: 'Bevorzugte Sprache',
    currencyPref: 'Bevorzugte Währung',
    profileTitle: 'Reiseprofil',
    budgetLabel: 'Günstig',
    moderateLabel: 'Mittel',
    luxuryLabel: 'Luxus',
    solo: 'Allein',
    couple: 'Paar',
    family: 'Familie',
    friends: 'Freunde'
  },
  ja: {
    brandName: 'イージートリップ',
    brandTagline: 'スマート旅のパートナー',
    navDashboard: 'ダッシュボード',
    navPlanner: 'AI旅行プランナー',
    navCurrentTrip: '現在の旅行',
    navProfile: 'プロフィール',
    askAI: 'AIに質問',
    signIn: 'ログイン',
    signOut: 'ログアウト',
    welcomeTitle: 'おかえりなさい',
    welcomeSubtitle: '次はどこへ旅に出かけますか？',
    createTripBtn: '新しい旅行を計画',
    myTrips: 'マイ旅行プラン',
    quickStats: '旅行の概要',
    totalTrips: '合計旅行数',
    noTripsYet: 'まだ旅行プランがありません',
    startPlanning: 'AIと一緒に理想の旅の計画を始めましょう。',
    viewDetails: 'プランを見る',
    exportPdf: 'PDFを出力',
    deleteTrip: '削除',
    plannerTitle: '理想の旅行をデザイン',
    plannerSubtitle: 'AIがマップ、予算見積もり、おすすめホテル、穴場スポットを含む日別の旅行プランを自動作成します。',
    destinationLabel: '目的地',
    destinationPlaceholder: '例：東京、パリ、京都、沖縄...',
    datesLabel: '旅行日程',
    startDate: '開始日',
    endDate: '終了日',
    durationDays: '日数',
    currencyAndBudget: '通貨 & 目標予算',
    budgetTier: '予算ランク',
    travelerGroup: '旅行スタイル',
    interestsLabel: '興味・こだわり',
    generateTripBtn: 'AIでプランを作成',
    generatingTrip: 'あなただけの特別プランを作成中...',
    tabItinerary: '旅程スケジュール',
    tabMap: 'インタラクティブマップ',
    tabHotels: 'おすすめホテル',
    tabWeather: '天気予報',
    tabPacking: '持ち物リスト',
    tabFood: 'グルメガイド',
    tabGems: '穴場スポット',
    tabBudget: '予算アナリティクス',
    tabEmergency: '緊急・安全情報',
    tabExpenses: '割り勘計算',
    day: '日目',
    chatTitle: 'イージートリップ AIアシスタント',
    chatSubtitle: '24時間いつでも頼れる旅の相棒',
    chatPlaceholder: '旅行について何でも聞いてください...',
    send: '送信',
    languagePref: '優先言語',
    currencyPref: '優先通貨',
    profileTitle: '旅行者プロフィール',
    budgetLabel: '節約',
    moderateLabel: '標準',
    luxuryLabel: 'ラグジュアリー',
    solo: '一人旅',
    couple: 'カップル',
    family: 'ファミリー',
    friends: '友達同士'
  }
};

export function detectBrowserLanguage(): string {
  if (typeof window === 'undefined') return 'en';
  
  const saved = localStorage.getItem('easytrip_language') || localStorage.getItem('travelmate_language');
  if (saved && SUPPORTED_LANGUAGES.some(l => l.code === saved)) {
    return saved;
  }

  const browserLang = navigator.language || (navigator as unknown as { userLanguage?: string }).userLanguage || 'en';
  const shortCode = browserLang.toLowerCase().split('-')[0];
  
  const matched = SUPPORTED_LANGUAGES.find(l => l.code === shortCode);
  return matched ? matched.code : 'en';
}

interface LanguageContextType {
  language: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
  getLanguageName: (code?: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
  getLanguageName: () => 'English',
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<string>(() => detectBrowserLanguage());

  const setLanguage = (code: string) => {
    setLanguageState(code);
    if (typeof window !== 'undefined') {
      localStorage.setItem('easytrip_language', code);
    }
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS['en'];
    return langDict[key] || TRANSLATIONS['en'][key] || key;
  };

  const getLanguageName = (code?: string): string => {
    const langCode = code || language;
    const found = SUPPORTED_LANGUAGES.find(l => l.code === langCode);
    return found ? `${found.nativeName} (${found.name})` : 'English';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
